# Basic options
title: Introduction to High Performance Computing and ISCA
short_name: Intro to ISCA
developers: Matthew West & Eilis Hannon
description: Learn what a HPC system is, and how to use it to increase the computational power of your research.
n_sessions: 2
prereq: Intro to UNIX
url: https://uniexeterrse.github.io/intro-to-isca
notes_on: false


# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
    sort_by: lesson

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Build settings
theme: jekyll-theme-slate
